# Generated by Django 3.2.8 on 2021-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('website_url', models.URLField()),
                ('email_address', models.EmailField(max_length=254)),
                ('telephone_no', models.CharField(max_length=10)),
                ('ccas', models.JSONField()),
                ('subjects', models.JSONField()),
                ('cutoff', models.JSONField()),
                ('courses', models.JSONField()),
            ],
        ),
    ]
