# Generated by Django 3.2.8 on 2021-10-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211023_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='ccs',
            new_name='ccas',
        ),
    ]
