# Generated by Django 3.2.8 on 2021-11-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ccs_school_ccas'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='distance',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='eta',
            field=models.FloatField(default=-1),
        ),
    ]
